resolvers:
    - 1.1.1.1:53
    - 1.0.0.1:53
    - 8.8.8.8:53
    - 8.8.4.4:53
    - 9.9.9.9:53
    - 9.9.9.10:53
    - 77.88.8.8:53
    - 77.88.8.1:53
    - 208.67.222.222:53
    - 208.67.220.220:53
sources:
    - alienvault
    - anubis
    - bufferover
    - certspotter
    - censys
    - chaos
    - crtsh
    - dnsdumpster
    - hackertarget
    - intelx
    - passivetotal
    - robtex
    - riddler
    - securitytrails
    - shodan
    - spyse
    - sublist3r
    - threatcrowd
    - threatminer
    - virustotal
all-sources:
    - alienvault
    - anubis
    - archiveis
    - binaryedge
    - bufferover
    - censys
    - certspotter
    - chaos
    - commoncrawl
    - crtsh
    - dnsdumpster
    - dnsdb
    - github
    - hackertarget
    - intelx
    - passivetotal
    - rapiddns
    - riddler
    - recon
    - robtex
    - securitytrails
    - shodan
    - sitedossier
    - sonarsearch
    - spyse
    - sublist3r
    - threatbook
    - threatcrowd
    - threatminer
    - virustotal
    - waybackarchive
    - zoomeye
recursive:
    - alienvault
    - binaryedge
    - bufferover
    - certspotter
    - crtsh
    - dnsdumpster
    - hackertarget
    - passivetotal
    - securitytrails
    - sonarsearch
    - sublist3r
    - virustotal
binaryedge: 
    - bcdb8059-4937-41c4-aca0-ac7fd5be9808
censys: 
    - ea4bf953-fac6-4155-ab1a-0ca1f8a4f09f:8wKxHBaMvuRelCNgLwZ3OsUsGUvyyBua
certspotter: 
    - 36502_h5nXbwxjo8bfIBELRLrQ
chaos:
    - 5c97a054a7106503b2fd605af22ce53cf4784d59e4005b442355b3f130af98d
dnsdb: 
    - dce-0c591496374196bb0082317210d3cdde60450d264393d023366ed5cb7dc1
github: 
    - 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
    - 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
intelx: 
    - f1e13acb-5c26-49ec-82ed-6d9d66e78864
passivetotal: 
    - iamdeviner@gmail.com:da48abcc9b86cb7060c19edd289937682c6b439e4651e6d6ba4437a3256608c7
recon: []
robtex: 
    - jXAua5PC9CzY5ZJwyLPK
securitytrails: 
    - fDaYyTSilfkhYwe3f3zhFGcA1atiaBEH
shodan: 
    - I74VE5bOEJ6RthIVYXQO44f31DTY4kAS
spyse: []
threatbook: []
urlscan: 
    - 699fad13-9f59-49fe-8efb-9f2def8ecd0c
virustotal: 
    - 3fa1966c86a1f98e4d62c8e32e33d3fb40718384a7d785fb695d8b9fd7c8c04c
zoomeye: []
subfinder-version: 2.4.6
